Librarie/LibrarieOnline/Controllers/AchizitieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibrarieOnline.Controllers
{
    public class AchizitieController : Controller
    {
        // GET: Achizitie
        public ActionResult Index()
        {
            return View();
        }
    }
}

Librarie/LibrarieOnline/Controllers/AuthController.cs
using System.Web.Mvc;
using System.Linq;
using LibrarieOnline.Model;
using System.Web.Security;
using System.Collections.Generic;
using System.Web;

namespace LibrarieOnline.Controllers
{
    public class AuthController : Controller
    {
        public readonly LibrarieEntities DB;
        public AuthController()
        {
            DB = new LibrarieEntities();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User data)
        {
            FormsAuthentication.SetAuthCookie(data.UserName, false);
            var check = DB.User.FirstOrDefault(u => u.UserName.Equals(data.UserName) && u.Password == data.Password);
            if (check!=null)
            {
                return RedirectToAction("Index","Home",data);
            }
            
            return View();
        }


        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }
        
        [HttpPost]
        [AllowAnonymous]
        public JsonResult GetRoles()
        {
            List<UserRole> result = new List<UserRole>();
            List<UserRole> toateRolurileExtraseDinDB = DB.UserRole.ToList();
            foreach (UserRole role in toateRolurileExtraseDinDB)
            {
                result.Add(new UserRole()
                {
                    Role = role.Role,
                    RoleId = role.RoleId
                });
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Registration(User data)
        {
            User obj = new User();
            obj.UserName = data.UserName;
            obj.Password = data.Password;
            obj.RoleId = data.RoleId;

            DB.User.Add(obj);
            DB.SaveChanges();

            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {

            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Auth");
            
        }
    }
}

Librarie/LibrarieOnline/Controllers/BookController.cs
using LibrarieOnline.Model;
using LibrarieOnline.Model.DTO;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace LibrarieOnline.Controllers
{
    public class BookController : Controller
    {
        public readonly LibrarieEntities DB;
        public BookController()
        {
            DB = new LibrarieEntities();
        }

        [Authorize(Roles = "admin")]
        public ActionResult UploadFiles()
        {
            BookViewModel obj = new BookViewModel();

            obj.author = DB.Author.ToList();
            obj.category = DB.Category.ToList();
            obj.publisher = DB.Publisher.ToList();
            return View(obj);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult UploadFiless()
        {
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase file = files[0];
            BinaryReader binaryReader = new BinaryReader(file.InputStream);
            byte[] imageInBinaryFormat = binaryReader.ReadBytes(file.ContentLength);

            try
            {
                Book book = DB.Book.Create();

                book.Title = Request.Form["Title"];
                book.Price = Convert.ToDouble(Request.Form["Price"]);
                book.CategoryId = Convert.ToInt32(Request.Form["DropDownCategoryId"]);
                book.AuthorId = Convert.ToInt32(Request.Form["DropDownAuthorId"]);
                book.PublisherId = Convert.ToInt32(Request.Form["DropDownPublisherId"]);
                book.Description = Request.Form["Description"];
                book.Image = imageInBinaryFormat;
                book.DateWhenWasAdded = DateTime.Now;

                DB.Book.Add(book);
                DB.SaveChanges();

            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }

            return Json("Succes", JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetBooks()
        {
            var Books = DB.Book.ToList();

            return View(Books);
        }
    }
}

Librarie/LibrarieOnline/Controllers/ContController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibrarieOnline.Controllers
{
    public class ContController : Controller
    {
        // GET: Cont
        public ActionResult Index()
        {
            return View();
        }
    }
}

Librarie/LibrarieOnline/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


namespace LibrarieOnline.Controllers
{
    public class HomeController : Controller
    {

        
        // GET: Home
        public ActionResult Index()
        {
            
            return View();
        }

        [Authorize(Roles ="admin")]
        public ActionResult About()
        {

            return View();
        }

    }
}

Librarie/LibrarieOnline/Views/Book/GetBooks.cshtml
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Category</th>
                <th>Author</th>
                <th>Publisher</th>
                <th>Description</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>@book.Price</td>
                    <td>@book.Category.Name</td>
                    <td>@book.Author.Name</td>
                    <td>@book.Publisher.Name</td>
                    <td>@book.Description</td>
                    <td>
                        <img src="data:image;base64,@System.Convert.ToBase64String(book.Image)" height="100px"/>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Librarie/LibrarieOnline/Views/Book/UploadFiles.cshtml
@model LibrarieOnline.Model.DTO.BookViewModel

@{
    ViewBag.Title = "UploadFiles";
}

<h2>UploadFiles</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="Title" class="form-control" />
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="Price" class="form-control" />

                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @{
                var categories = new List<SelectListItem>();
                foreach (var item in Model.category)
                {
                    categories.Add(new SelectListItem() { Text = item.Name, Value = item.CategoryId.ToString() });
                }
            }

            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            @Html.DropDownList("CategoryDropDown", categories, htmlAttributes: new { @class = "form-control" })
            <br />
        </div>

        <div class="form-group">
            @{
                var author = new List<SelectListItem>();
                foreach (var item in Model.author)
                {
                    author.Add(new SelectListItem() { Text = item.Name, Value = item.AuthorId.ToString() });
                }
            }

            @Html.LabelFor(model => model.AuthorId, "AuthorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            @Html.DropDownList("AuthorDropDown", author, htmlAttributes: new { @class = "form-control" })
            <br />
        </div>

        <div class="form-group">
            @{
                var publisher = new List<SelectListItem>();
                foreach (var item in Model.publisher)
                {
                    publisher.Add(new SelectListItem() { Text = item.Name, Value = item.PublisherId.ToString() });
                }
            }

            @Html.LabelFor(model => model.PublisherId, "PublisherId", htmlAttributes: new { @class = "control-label col-md-2" })
            <br />
            @Html.DropDownList("PublisherDropDown", publisher, htmlAttributes: new { @class = "form-control" })
            <br />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="Description" class="form-control" />
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" class="form-control" id="image">
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="UploadBtn" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script>
        $('#UploadBtn').click(function () {           
            var formData = new FormData();
            formData.append($("#image").get(0).files[0].name, $("#image").get(0).files[0]);
            formData.append("DropDownAuthorId", $('[name="AuthorDropDown"]').val());
            formData.append("DropDownPublisherId", $('[name="PublisherDropDown"]').val());
            formData.append("DropDownCategoryId", $('[name="CategoryDropDown"]').val());
            formData.append("Title", $('#Title').val());
            formData.append("Description", $('#Description').val());
            formData.append("Price", $('#Price').val());

            $.ajax({
                url: '@Url.Action("UploadFiless", "Book")',
                type: "POST",
                contentType: false,
                processData: false,
                data: formData,
                async: false,
                success: function () {                    
                    alert("succes");                    
                },
                error: function () {
                    alert("ERROR");
                }
            });

        });
</script>

Librarie/LibrarieOnline/Views/Home/About.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h1>About Page!</h1>
</body>
</html>

Librarie/LibrarieOnline/Views/Home/Index.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>

    <h1>Home Page! </h1>

</body>
</html>

Librarie/LibrarieOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>

    <style>
        .myNavbar {
            background-color: blue;
            margin-bottom: 30px;
            height: 52px;
        }

        .myNavbarContent {
            background-color: aqua;
            width: 75%;
            margin: auto;
            height: 52px;
        }
    </style>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="myNavbar">
        <div class="myNavbarContent">
            @Html.ActionLink("Home", "Index", "Home", new { }, new { })
            @Html.ActionLink("About", "About", "Home", new { }, new { })
            @Html.ActionLink("Contact", "", "", new { }, new { })

            @if (User.Identity.IsAuthenticated)
            {

                if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("UploadBook", "UploadFiles", "Book", new { }, new { })
                }

                if (User.IsInRole("user"))
                {
                    @Html.ActionLink("Charge Your Account", "Index", "Cont", new { }, new { })
                    @Html.ActionLink("Achizitii", "Index", "Achizitie", new { }, new { })

                }
            }
            <div style="float: right">
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Logout", "Logout", "Auth", new { }, new { })
                }
                else
                {
                    @Html.ActionLink("Login", "Login", "Auth", new { }, new { })
                    @Html.ActionLink("Registration", "Registration", "Auth", new { }, new { })
                }
            </div>
        </div>
    </div>

    @RenderBody()
</body>
</html>